### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lucasmr** [jorgicio/mate-jorgicio#1]
cpufreq-monitor-libcpufreq.o: In function `cpufreq_monitor_libcpufreq_run':
cpufreq-monitor-libcpufreq.c:(.text+0x337): undefined reference to `cpupower_is_cpu_online'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:584: mate-cpufreq-applet] Error 1
make[4]: Leaving directory '/home/portage/tmp/portage/mate-base/mate-applets-1.14.1/work/mate-applets-1.14.1/cpufreq/src'
make[3]: *** [Makefile:638: all-recursive] Error 1
make[3]: Leaving directory '/home/portage/tmp/portage/mate-base/mate-applets-1.14.1/work/mate-applets-1.14.1/cpufreq/src'
make[2]: *** [Makefile:610: all-recursive] Error 1
make[2]: Leaving directory '/home/portage/tmp/portage/mate-base/mate-applets-1.14.1/work/mate-applets-1.14.1/cpufreq'
make[1]: *** [Makefile:574: all-recursive] Error 1
make[1]: Leaving directory '/home/portage/tmp/portage/mate-base/mate-applets-1.14.1/work/mate-applets-1.14.1'
make: *** [Makefile:506: all] Error 2

**Comment by jorgicio** [comment]
That's weird.
It uses sys-power/cpupower as a library and it must be installed first. I did some changes though. Resync and try again.

**Comment by lucasmr** [comment]
Nope, not even emerge--oneshot cpupower solves the compilation.

**Comment by jorgicio** [comment]
Hmmmm... please, paste your emerge --info and the log file for the package you're trying to build.

**Comment by lucasmr** [comment]
# emerge --info
Portage 2.3.0 (python 3.4.5-final-0


, default/linux/amd64/13.0, gcc-5.4.0, glibc-2.23-r2, 4.7.0-gentoo x86_64)
=================================================================
System uname: Linux-4.7.0-gentoo-x86_64-Intel-R-_Core-TM-_i5-3570K_CPU_@_3.40GHz-with-gentoo-2.3
KiB Mem:     8059300 total,   3903028 free
KiB Swap:    8388604 total,   8388604 free
Timestamp of repository gentoo: Sun, 11 Sep 2016 14:30:01 +0000
sh bash 4.3_p46
ld GNU ld (Gentoo 2.26.1 p1.0) 2.26.1
app-shells/bash:          4.3_p46::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.24.0-r1::gentoo
dev-lang/python:          2.7.12::gentoo, 3.4.5::gentoo
dev-util/cmake:           3.6.2::gentoo
dev-util/pkgconfig:       0.29.1::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.21.7::gentoo
sys-apps/sandbox:         2.10-r2::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r2::gentoo
sys-devel/automake:       1.11.6-r2::gentoo, 1.13.4-r1::gentoo, 1.14.1-r1::gentoo, 1.15-r2::gentoo
sys-devel/binutils:       2.26.1::gentoo
sys-devel/gcc:            5.4.0::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r2::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.7::gentoo (virtual/os-headers)
sys-libs/glibc:           2.23-r2::gentoo
Repositories:

gentoo
    location: /home/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

steam-overlay
    location: /usr/local/steam-overlay
    sync-type: git
    sync-uri: https://github.com/anyc/steam-overlay/
    masters: gentoo

abendbrot
    location: /var/lib/layman/abendbrot
    masters: gentoo
    priority: 50

java
    location: /var/lib/layman/java
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    masters: gentoo
    priority: 50

mate-jorgicio
    location: /var/lib/layman/mate-jorgicio
    masters: gentoo
    priority: 50

obs-studio-overlay
    location: /var/lib/layman/obs-studio-overlay
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe -fomit-frame-pointer"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -O2 -pipe -fomit-frame-pointer"
DISTDIR="/home/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://gentoo.c3sl.ufpr.br/ http://www.las.ic.unicamp.br/pub/gentoo/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/home/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/home/portage/tmp"
USE="X acl amd64 berkdb bzip2 cli consolekit cracklib crypt cxx dbus dri fortran gdbm gnome-keyring iconv ipv6 mmx mmxext modules multilib ncurses networkmanager nls nptl openmp pam pcre pulseaudio readline seccomp session sse sse2 ssl tcpd truetype udev unicode vdpau xattr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="nouveau intel" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON


build log: [http://pastebin.com/Mt1g1Q3U](url)

**Comment by jorgicio** [comment]
Ok, I found your problem: you're using all system in ~amd64, so the kernel you're using is the 4.7 branch. Some changes were done since then, so I patched and upgraded mate-applets to -r1. Resync and do an `emerge @world`.

**Comment by lucasmr** [comment]
Still no dice, same problem.

**Comment by jorgicio** [comment]
Be aware of not using cpupower-4.7, which is now masked. Here works flawlessly, so there's something more... also, that issue was fixed upstream. I recommend using cpupower-4.5 as the latest version.
And don't to forget to do a resync and an `emerge @world`.

**Comment by lucasmr** [comment]
Odd, I got cpupower-4.5.0-r1 and still can't compile...

**Comment by jorgicio** [comment]
It may be a problem with GCC then. I'm using the stable one (4.9.3). I don't know if it had to do with that, but just in case, try downgrading. Also, GCC is an essential package for compiling Gentoo and, as a good practice, try to avoid using the ~arch version but use the stable one.
Try with that and tell me what's going on. If still the same issue, try to use the stable version of the kernel (4.4.6).

**Comment by lucasmr** [comment]
# uname -a
Linux lucas=pc 4.4.6-gentoo #1 SMP Fri Sep 16 15:23:52 BRT 2016 x86_64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz GenuineIntel GNU/Linux

# gcc --version
gcc (Gentoo 4.9.3 p1.5, pie-0.6.4) 4.9.3

# equery l cpupower
 * Searching for cpupower ...
[IP-] [  ] sys-power/cpupower-4.5.0-r1:0

Same compilation error. Also tried redownloading the packages, so not corrupted I guess.

**Comment by jorgicio** [comment]
Ok, I'll inspect that and find what's going on, because this was fixed in upstream as mentioned here: https://github.com/mate-desktop/mate-applets/issues/193
Also, tried editing by hand the file in question. The library cpuidle.h is only available since kernel 4.7 and its headers (I'm using linux-headers-4.3). The compilation fails when I force to include cpuidle.h (cannot be found) and then repatching and forcing to use the cpupower_is_cpu_online and fails again. When I restore to the current status I uploaded to this repo, all went fine.
If you're using an older kernel, it won't use the cpupower_is_cpu_online, but its alternative. Try downgrading the linux-headers to its stable version and try again. If still fails, there's a lot a work to do. But it must build fine.

**Comment by lucasmr** [comment]
Right, with linux-headers-4.3 it compiles succesfully.

**Comment by jorgicio** [comment]
Thanks. I'll left this issue open to find some workaround to rid that. Meanwhile, I suggest to use that version of linux-headers.

**Comment by lucasmr** [comment]
Thank you. Maybe upstream didn't fix it after all?

**Comment by jorgicio** [comment]
Maybe because it looks for a kernel version, not a headers version.

**Comment by jorgicio** [comment]
MATE upgraded to version 1.16.0, so I bumped it. Resync, upgrade, and try again with the most recent version of linux-headers to test if fails because this issue may be fixed in upstream.

**Comment by lucasmr** [comment]
Mate 1.16 fixes this, compiling with linux-headers-4.7.

**Comment by jorgicio** [comment]
Thank you! I'll asume this issue was fixed in upstream. Enjoy MATE 1.16!
